.container {
    max-width: 800px;
    margin: 0 auto;
    padding: 2rem;
    background-color: #1a1a1a;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.5);
    color: #ededed;
    margin-top: 4rem;
  }
  
  .title {
    font-size: 2.5rem;
    color: #00bfff;
    margin-bottom: 1rem;
    text-align: center;
  }
  
  .genre {
    font-size: 1.2rem;
    color: #888;
    margin-bottom: 1rem;
    text-align: center;
  }
  
  .description {
    font-size: 1rem;
    color: #ccc;
    margin-bottom: 1.5rem;
    text-align: justify;
  }
  
  .imageWrapper {
    position: relative;
    width: 100%;
    height: 0;
    padding-bottom: 56.25%; /* 16:9 aspect ratio */
    margin-bottom: 1.5rem;
    border-radius: 8px;
    overflow: hidden;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.5);
  }
  
  .image {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
  
  .releaseDate {
    font-size: 1rem;
    color: #aaa;
    text-align: center;
  }